import { useState } from 'react';
import { Upload, FileCode, FileText, TestTube, Sparkles } from 'lucide-react';
import Editor from '@monaco-editor/react';

interface ProcessingStatus {
  analyzing: boolean;
  generating: boolean;
  complete: boolean;
}

function App() {
  const [selectedFile, setSelectedFile] = useState<string>('');
  const [fileContent, setFileContent] = useState<string>('# Upload a Python, JavaScript, TypeScript, C++, or Java file to see preview\n# Click the upload button above to get started');
  const [outputType, setOutputType] = useState<'documentation' | 'tests' | 'refactor' | 'all'>('all');
  const [status, setStatus] = useState<ProcessingStatus>({
    analyzing: false,
    generating: false,
    complete: false,
  });
  const [generatedOutput, setGeneratedOutput] = useState<string>('');

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setSelectedFile(file.name);
      const reader = new FileReader();
      reader.onload = (e) => {
        const content = e.target?.result as string;
        setFileContent(content);
        console.log('File loaded:', file.name, 'Size:', content.length, 'chars');
      };
      reader.readAsText(file);
    }
  };

  const handleProcess = async () => {
    setStatus({ analyzing: true, generating: false, complete: false });
    
    await new Promise(resolve => setTimeout(resolve, 2000));
    setStatus({ analyzing: false, generating: true, complete: false });
    
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    let mockOutput = '';
    
    if (outputType === 'documentation' || outputType === 'all') {
      mockOutput = `\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{listings}
\\title{Technical Documentation: ${selectedFile}}
\\author{Generated by Q-Sync with IBM Bob}
\\date{\\today}
\\begin{document}
\\maketitle
\\section{Overview}
This module implements quantum trajectory simulation for spacecraft optimization.
\\section{Architecture}
Uses Cirq framework with quantum annealing for delta-v optimization.
\\end{document}`;
    } else if (outputType === 'tests') {
      mockOutput = `import pytest
import numpy as np

class TestQuantumCircuit:
    def test_initialization(self):
        simulator = QuantumTrajectorySimulator(num_qubits=8)
        assert simulator.num_qubits == 8
    
    def test_superposition(self):
        simulator = QuantumTrajectorySimulator()
        simulator.create_superposition()
        assert len(list(simulator.circuit.all_operations())) > 0`;
    } else {
      mockOutput = `# Refactored and optimized code
import numpy as np
import cirq
from typing import Tuple

class QuantumTrajectorySimulator:
    """Optimized quantum trajectory simulator"""
    
    def __init__(self, num_qubits: int = 8) -> None:
        if num_qubits <= 0:
            raise ValueError("num_qubits must be positive")
        self.num_qubits = num_qubits
        self.qubits = cirq.LineQubit.range(num_qubits)
        self.circuit = cirq.Circuit()`;
    }
    
    setGeneratedOutput(mockOutput);
    setStatus({ analyzing: false, generating: false, complete: true });
  };

  return (
    <div className="h-screen w-screen flex flex-col bg-cosmic-dark text-white">
      <header className="h-banner bg-gradient-to-r from-cosmic-dark to-cosmic-darker flex items-center justify-center border-b border-cosmic-green/20">
        <div className="flex items-center gap-3">
          <Sparkles className="w-8 h-8 text-cosmic-green" />
          <h1 className="text-3xl font-bold tracking-wider">
            Q-Sync <span className="text-cosmic-green">|</span> Quantum-Bob Accelerator
          </h1>
        </div>
      </header>

      <main className="h-workspace flex">
        <aside className="w-80 bg-cosmic-darker border-r border-cosmic-green/20 p-6 flex flex-col gap-6 overflow-y-auto">
          <div>
            <h2 className="text-xl font-semibold mb-4 text-cosmic-green">1. Upload Repository</h2>
            <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-cosmic-purple/50 rounded-lg cursor-pointer hover:border-cosmic-green/50 transition-colors">
              <Upload className="w-8 h-8 text-cosmic-purple mb-2" />
              <span className="text-sm text-gray-400 text-center px-2">
                {selectedFile || 'Drag & drop or click to upload'}
              </span>
              <input
                type="file"
                className="hidden"
                onChange={handleFileUpload}
                accept=".py,.js,.ts,.cpp,.java"
              />
            </label>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-4 text-cosmic-green">2. Select Output</h2>
            <div className="space-y-2">
              {[
                { value: 'documentation', icon: FileText, label: 'Documentation (LaTeX)' },
                { value: 'tests', icon: TestTube, label: 'Unit Tests' },
                { value: 'refactor', icon: FileCode, label: 'Refactored Code' },
                { value: 'all', icon: Sparkles, label: 'All Outputs' },
              ].map(({ value, icon: Icon, label }) => (
                <button
                  key={value}
                  onClick={() => setOutputType(value as any)}
                  className={`w-full flex items-center gap-3 p-3 rounded-lg transition-colors ${
                    outputType === value
                      ? 'bg-cosmic-green/20 border border-cosmic-green'
                      : 'bg-cosmic-dark/50 border border-transparent hover:border-cosmic-purple/50'
                  }`}
                >
                  <Icon className="w-5 h-5" />
                  <span className="text-sm">{label}</span>
                </button>
              ))}
            </div>
          </div>

          <div className="mt-auto">
            <h2 className="text-xl font-semibold mb-4 text-cosmic-green">3. Process</h2>
            <button
              onClick={handleProcess}
              disabled={!selectedFile || status.analyzing || status.generating}
              className="w-full bg-cosmic-green text-cosmic-dark font-semibold py-3 rounded-lg hover:bg-cosmic-green/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {status.analyzing
                ? '🔍 Analyzing with Bob...'
                : status.generating
                ? '⚡ Generating Output...'
                : status.complete
                ? '✅ Complete!'
                : '🚀 Start Processing'}
            </button>
          </div>

          {(status.analyzing || status.generating || status.complete) && (
            <div className="space-y-2 text-sm">
              <div className={`flex items-center gap-2 ${status.analyzing ? 'text-cosmic-green' : 'text-gray-500'}`}>
                <div className={`w-2 h-2 rounded-full ${status.analyzing ? 'bg-cosmic-green animate-pulse' : 'bg-gray-500'}`} />
                Repository Analysis
              </div>
              <div className={`flex items-center gap-2 ${status.generating ? 'text-cosmic-green' : 'text-gray-500'}`}>
                <div className={`w-2 h-2 rounded-full ${status.generating ? 'bg-cosmic-green animate-pulse' : 'bg-gray-500'}`} />
                Output Generation
              </div>
              <div className={`flex items-center gap-2 ${status.complete ? 'text-cosmic-green' : 'text-gray-500'}`}>
                <div className={`w-2 h-2 rounded-full ${status.complete ? 'bg-cosmic-green' : 'bg-gray-500'}`} />
                Ready to Export
              </div>
            </div>
          )}
        </aside>

        <section className="flex-1 flex flex-col">
          <div className="bg-cosmic-darker border-b border-cosmic-green/20 px-6 py-3">
            <h2 className="text-lg font-semibold text-cosmic-purple">
              {selectedFile ? `Preview: ${selectedFile}` : 'No file selected'}
            </h2>
          </div>
          <div className="flex-1 relative">
            <div className="absolute inset-0">
              <Editor
                height="100%"
                defaultLanguage="python"
                theme="vs-dark"
                value={fileContent}
                options={{
                  readOnly: true,
                  minimap: { enabled: true },
                  fontSize: 14,
                  lineNumbers: 'on',
                  scrollBeyondLastLine: false,
                  wordWrap: 'on',
                  automaticLayout: true,
                }}
              />
            </div>
          </div>
        </section>

        <aside className="w-96 bg-cosmic-darker border-l border-cosmic-green/20 p-6 flex flex-col overflow-y-auto">
          <h2 className="text-xl font-semibold mb-4 text-cosmic-green">Generated Output</h2>
          
          {status.complete ? (
            <div className="flex-1 flex flex-col gap-4">
              <div className="bg-cosmic-dark/50 rounded-lg p-4 border border-cosmic-green/20">
                <h3 className="font-semibold mb-2 text-cosmic-purple">Statistics</h3>
                <div className="space-y-1 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-400">Time Saved:</span>
                    <span className="text-cosmic-green font-semibold">74h 45m</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Lines Generated:</span>
                    <span className="text-cosmic-green font-semibold">1,247</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Test Coverage:</span>
                    <span className="text-cosmic-green font-semibold">98%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Bobcoins Used:</span>
                    <span className="text-cosmic-green font-semibold">8 / 40</span>
                  </div>
                </div>
              </div>

              <div className="flex-1 bg-cosmic-dark/50 rounded-lg p-4 border border-cosmic-purple/20 overflow-auto">
                <h3 className="font-semibold mb-2 text-cosmic-purple">Output Preview</h3>
                <pre className="text-xs text-gray-300 whitespace-pre-wrap font-mono">
                  {generatedOutput}
                </pre>
              </div>

              <button className="w-full bg-cosmic-purple text-white font-semibold py-3 rounded-lg hover:bg-cosmic-purple/90 transition-colors">
                📥 Download All Files
              </button>
            </div>
          ) : (
            <div className="flex-1 flex items-center justify-center text-gray-500">
              <div className="text-center">
                <Sparkles className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>Process a file to see generated output</p>
              </div>
            </div>
          )}
        </aside>
      </main>
    </div>
  );
}

export default App;
