import dotenv from 'dotenv';

dotenv.config();

const watsonxApiKey = process.env.WATSONX_API_KEY;
const watsonxProjectId = process.env.WATSONX_PROJECT_ID;
const watsonxUrl = process.env.WATSONX_URL || 'https://us-south.ml.cloud.ibm.com';
const watsonxModelId = process.env.WATSONX_MODEL_ID || 'ibm/granite-3-1-8b-instruct';

if (!watsonxApiKey || !watsonxProjectId) {
  console.warn('⚠️ watsonx.ai credentials not found. Using mock mode.');
}

let watsonxClient: any = null;
let iamToken: string | null = null;
let tokenExpiry: number = 0;

async function getIAMToken(): Promise<string> {
  // Check if token is still valid (with 5 minute buffer)
  if (iamToken && Date.now() < tokenExpiry - 300000) {
    return iamToken;
  }

  if (!watsonxApiKey) {
    throw new Error('WATSONX_API_KEY not configured');
  }

  try {
    const response = await fetch('https://iam.cloud.ibm.com/identity/token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: `grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${watsonxApiKey}`,
    });

    if (!response.ok) {
      throw new Error(`IAM token request failed: ${response.statusText}`);
    }

    const data = await response.json();
    iamToken = data.access_token;
    tokenExpiry = Date.now() + (data.expires_in * 1000);
    
    return iamToken;
  } catch (error) {
    console.error('❌ Failed to get IAM token:', error);
    throw error;
  }
}

export async function initWatsonX() {
  if (!watsonxApiKey || !watsonxProjectId) {
    console.log('⚠️ watsonx.ai running in MOCK mode');
    return null;
  }

  try {
    // Test IAM token generation
    await getIAMToken();
    watsonxClient = { initialized: true };
    console.log('✅ Connected to watsonx.ai');
    return watsonxClient;
  } catch (error) {
    console.error('❌ watsonx.ai connection failed:', error);
    console.log('⚠️ Falling back to MOCK mode');
    return null;
  }
}

export async function generateWithWatsonX(prompt: string, modelId?: string): Promise<string> {
  const model = modelId || watsonxModelId;

  if (!watsonxClient || !watsonxApiKey || !watsonxProjectId) {
    console.log('⚠️ Using MOCK watsonx.ai response');
    return generateMockResponse(prompt);
  }

  try {
    const token = await getIAMToken();
    
    const requestBody = {
      model_id: model,
      input: prompt,
      parameters: {
        max_new_tokens: 2000,
        temperature: 0.7,
        top_p: 0.9,
        top_k: 50,
        repetition_penalty: 1.1,
      },
      project_id: watsonxProjectId,
    };

    const response = await fetch(`${watsonxUrl}/ml/v1/text/generation?version=2024-05-31`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ watsonx.ai API error:', response.status, errorText);
      throw new Error(`watsonx.ai API error: ${response.statusText}`);
    }

    const data = await response.json();
    const generatedText = data.results?.[0]?.generated_text || '';
    
    console.log('✅ watsonx.ai generation successful');
    return generatedText;
  } catch (error) {
    console.error('❌ watsonx.ai generation failed:', error);
    console.log('⚠️ Falling back to MOCK response');
    return generateMockResponse(prompt);
  }
}

function generateMockResponse(prompt: string): string {
  if (prompt.includes('documentation') || prompt.includes('LaTeX')) {
    return `\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\title{Quantum Trajectory Simulation Documentation}
\\author{Generated by Q-Sync with IBM watsonx.ai Granite}
\\date{\\today}

\\begin{document}
\\maketitle

\\section{Overview}
This document provides comprehensive documentation for the quantum trajectory simulation system, designed for NASA aerospace applications and quantum computing research.

\\section{Architecture}
The system implements quantum state evolution using Qiskit and NumPy, optimized for high-performance computing environments.

\\subsection{Mathematical Foundation}
The quantum state evolution follows the Schrödinger equation:
\\begin{equation}
i\\hbar\\frac{\\partial}{\\partial t}|\\psi(t)\\rangle = \\hat{H}|\\psi(t)\\rangle
\\end{equation}

where $\\hat{H}$ is the Hamiltonian operator and $|\\psi(t)\\rangle$ represents the quantum state at time $t$.

\\section{Implementation Details}
The simulation uses the following key components:
\\begin{itemize}
\\item Quantum circuit initialization with configurable qubit count
\\item Superposition state preparation using Hadamard gates
\\item Measurement and optimization algorithms
\\item Error mitigation strategies for NISQ devices
\\end{itemize}

\\subsection{Performance Characteristics}
\\begin{itemize}
\\item Time complexity: $O(2^n)$ for $n$ qubits
\\item Space complexity: $O(2^n)$ for state vector storage
\\item Optimized for GPU acceleration
\\end{itemize}

\\section{Usage Examples}
See the accompanying test suite for comprehensive usage examples and best practices.

\\end{document}`;
  }

  if (prompt.includes('test') || prompt.includes('pytest')) {
    return `import pytest
import numpy as np
from quantum_trajectory_simulation import QuantumTrajectorySimulator

class TestQuantumTrajectorySimulator:
    """Comprehensive test suite for quantum trajectory simulation."""
    
    @pytest.fixture
    def simulator(self):
        """Create a simulator instance for testing."""
        return QuantumTrajectorySimulator(num_qubits=3)
    
    def test_initialization(self, simulator):
        """Test proper initialization of simulator."""
        assert simulator.num_qubits == 3
        assert simulator.circuit is not None
        assert simulator.backend is not None
    
    def test_superposition(self, simulator):
        """Test superposition state creation."""
        simulator.create_superposition()
        statevector = simulator.get_statevector()
        assert len(statevector) == 2**3
        # Verify equal superposition
        expected_amplitude = 1 / np.sqrt(2**3)
        np.testing.assert_allclose(
            np.abs(statevector), 
            expected_amplitude, 
            rtol=1e-5
        )
    
    @pytest.mark.parametrize("num_qubits", [2, 3, 4, 5])
    def test_scalability(self, num_qubits):
        """Test simulator scalability with different qubit counts."""
        sim = QuantumTrajectorySimulator(num_qubits=num_qubits)
        assert sim.num_qubits == num_qubits
        sim.create_superposition()
        statevector = sim.get_statevector()
        assert len(statevector) == 2**num_qubits
    
    def test_measurement(self, simulator):
        """Test measurement functionality."""
        simulator.create_superposition()
        results = simulator.measure(shots=1000)
        assert len(results) > 0
        assert all(isinstance(r, (int, float)) for r in results.values())
        # Verify measurement probabilities sum to 1
        total_prob = sum(results.values()) / 1000
        assert abs(total_prob - 1.0) < 0.01
    
    def test_error_handling(self):
        """Test error handling for invalid inputs."""
        with pytest.raises(ValueError):
            QuantumTrajectorySimulator(num_qubits=0)
        with pytest.raises(ValueError):
            QuantumTrajectorySimulator(num_qubits=-1)
    
    def test_state_persistence(self, simulator):
        """Test that quantum state persists correctly."""
        simulator.create_superposition()
        state1 = simulator.get_statevector()
        state2 = simulator.get_statevector()
        np.testing.assert_array_equal(state1, state2)`;
  }

  if (prompt.includes('refactor') || prompt.includes('optimize')) {
    return `from typing import List, Dict, Optional, Union
import numpy as np
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.providers import Backend
import logging

logger = logging.getLogger(__name__)

class QuantumTrajectorySimulator:
    """
    Optimized quantum trajectory simulator with type hints and error handling.
    
    This class provides a high-performance interface for quantum circuit
    simulation with support for various backends and optimization strategies.
    """
    
    def __init__(
        self, 
        num_qubits: int, 
        backend: Optional[Union[str, Backend]] = None
    ) -> None:
        """
        Initialize the quantum trajectory simulator.
        
        Args:
            num_qubits: Number of qubits in the quantum circuit
            backend: Qiskit backend to use for simulation
            
        Raises:
            ValueError: If num_qubits is not positive
        """
        if num_qubits < 1:
            raise ValueError("num_qubits must be positive")
        
        self.num_qubits = num_qubits
        self.backend = backend or 'qasm_simulator'
        self._initialize_circuit()
        logger.info(f"Initialized simulator with {num_qubits} qubits")
    
    def _initialize_circuit(self) -> None:
        """Initialize quantum circuit with registers."""
        qr = QuantumRegister(self.num_qubits, 'q')
        cr = ClassicalRegister(self.num_qubits, 'c')
        self.circuit = QuantumCircuit(qr, cr)
        logger.debug("Circuit initialized successfully")
    
    def create_superposition(self) -> None:
        """
        Create superposition state using vectorized operations.
        
        Applies Hadamard gates to all qubits to create an equal
        superposition of all basis states.
        """
        # Vectorized Hadamard gates for better performance
        for qubit in range(self.num_qubits):
            self.circuit.h(qubit)
        logger.debug("Superposition state created")
    
    def get_statevector(self) -> np.ndarray:
        """
        Get the current quantum state vector.
        
        Returns:
            Complex numpy array representing the quantum state
        """
        from qiskit.quantum_info import Statevector
        return Statevector(self.circuit).data
    
    def measure(self, shots: int = 1024) -> Dict[str, int]:
        """
        Perform measurements on the quantum circuit.
        
        Args:
            shots: Number of measurement shots to perform
            
        Returns:
            Dictionary mapping measurement outcomes to counts
        """
        from qiskit import execute, Aer
        
        # Add measurement gates
        self.circuit.measure_all()
        
        # Execute on backend
        backend = Aer.get_backend(self.backend)
        job = execute(self.circuit, backend, shots=shots)
        result = job.result()
        
        logger.info(f"Measurement complete with {shots} shots")
        return result.get_counts()`;
  }

  return 'Mock response generated by Q-Sync with IBM watsonx.ai';
}

export { watsonxClient };
